<div class="card col-md-4 offset-md-4">
    <div class="card-body">
            <h4 class="card-title">Ingresa al sistema</h4>
            <form method="POST">
                <fieldset>
                    <div class="form-group">
                        <label for="user">Ingresa tu rut</label>
                        <input type="text" class="form-control" id="rut" name="rut" aria-describedby="userHelp" placeholder="Ingresa tu rut sin puntos ni guión" required="required">
                        <small id="userHelp" class="form-text text-muted">Ingresa tu rut sin puntos ni guión, ejemplo: 112223334.</small>
                    </div>
                    <div class="form-group">
                        <label for="pass">Contraseña</label>
                        <input type="password" class="form-control" id="pass" name="pass" placeholder="Ingresa tu contraseña" required="required">
                    </div>
                </fieldset>

                <button class="btn btn-primary btn-block">Ingresar</button>
            </form>

        <?php if(!$params['status']) { ?>
            <br>
            <div class="alert alert-dismissible alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <p class="mb-0"><?= $params['msg'] ?></a>.</p>
            </div>
        <?php } ?>
    </div>
</div>
