<?php
switch ($session['role']) {
    case 2:
        View::partial('menu/teacher', '', 'index');
        break;
    case 3:
        View::partial('menu/psychoanalist', '', 'index');
        break;
    case 4:
        View::partial('menu/student', '', 'index');
        break;
    default :
        View::partial('menu/inicio', '', 'index');
        break;
}
?>
<?php  ?>

    <!-- Begin page content -->
    <main role="main" class="container">
        <div class="row">
            <?php
                switch ($session['role']) {
                    case 2:
                        View::partial('index/teacher', '', 'index');
                        break;
                    case 3:
                        View::partial('index/psycho', '', 'index');
                        break;
                    case 4:
                        View::partial('index/student', '', 'index');
                        break;
                    default :
                        View::partial('index/login', '', $status);
                        break;
                }
             ?>

        </div>
    </main>

