<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="<?= APP_CHARSET ?>" >
    <title>UIM - Universal Intranet Mobile</title>
    <?php Tag::css('bootstrap.min') ?>
    <?php Tag::css('main') ?>
    <?= Html::includeCss() ?>
    <!-- <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/bootstrap.min.css" > -->
</head>
<body>
    <?php View::content() ?>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">Place sticky footer content here.</span>
        </div>
    </footer>
<script src="<?= PUBLIC_PATH ?>javascript/jquery/jquery.min.js"></script>
</body>
</html>
