<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="<?= APP_CHARSET ?>" >
    <title>UIM - Universal Intranet Mobile</title>
    <?php Tag::css('bootstrap.min') ?>
    <?php Tag::css('main') ?>
    <?= Html::includeCss() ?>
    <!-- <link rel="stylesheet" href="<?= PUBLIC_PATH ?>css/bootstrap.min.css" > -->
</head>
<body>
    <?php View::content() ?>

    <footer class="footer">
        <div class="container">
            <span class="text-muted">UIM 2018. |  <?= 'Ejecutado en ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT']) * 1000, 4), ' ms. usando ', number_format(memory_get_usage() / 1048576, 3), ' MB de memoria'; ?></span>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="<?= PUBLIC_PATH ?>javascript/bootstrap.min.js"></script>
</body>
</html>
