<?php View::partial('menu/teacher', '', array('courses', $session['name'])); ?>

<main role="main" class="container">
    <div class="row">
        <div class="card col-md-8 offset-md-2">
            <div class="card-body">
                <h4 class="card-title"><?=$course->name?></h4>

                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#home">Estudiantes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#profile">Pruebas</a>
                    </li>
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade show active" id="home">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">Matrícula</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">F. Nacimiento</th>
                                <th scope="col">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($students as $stud) : ?>
                                <tr>
                                    <th scope="row"><?=$stud["registration"]?></th>
                                    <td><?=$stud["name"]?></td>
                                    <td><?=$stud["birth"]?></td>
                                    <td><a href="/student/profile/<?=$stud['id_est']?>" class="btn btn-sm btn-info">Ver Perfil</a></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="tab-pane fade" id="profile">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">Nombre</th>
                                <th scope="col">Descripción</th>
                                <th scope="col">Creación</th>
                                <th scope="col">F. Inicio</th>
                                <th scope="col">F. Termino</th>
                                <th scope="col">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($tests as $test) : ?>
                                <tr>
                                    <th><?=$test->name?></th>
                                    <td><?=$test->description?></td>
                                    <td><?=$test->creation?></td>
                                    <td><?=$test->start?></td>
                                    <td><?=$test->end?></td>
                                    <td><a href="/student/profile/<?=$test->id?>" class="btn btn-sm btn-info">Ver Prueba</a></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-md-4 offset-md-4">
                                <a href="/test/new/<?=$course->id?>" class="btn btn-block btn-primary">Crear prueba</a>
                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>
</main>
