<?php View::partial('menu/teacher', '', array('courses', $session['name'])); ?>

<main role="main" class="container">
    <div class="row">
        <div class="card col-md-8 offset-md-2">
            <div class="card-body">
                <h4 class="card-title">Mis cursos</h4>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Código</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Creación</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($courses as $course) : ?>
                    <tr>
                        <th scope="row"><?=$course->code?></th>
                        <td><?=$course->name?></td>
                        <td><?=$course->creation?></td>
                        <td><a href="/courses/detail/<?=$course->id?>" class="btn btn-sm btn-info">Ir</a></td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
